version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    networks:
      - xaldigital
    volumes:
      - ./database/init.d:/docker-entrypoint-initdb.d
  centos:
    image: centos/httpd-24-centos7
    ports:
      - 8080:8080
    networks:
      - xaldigital
    volumes:
      - ./Sample.csv:/var/www/html/Sample.csv
  api:
    container_name: nestjs-api
    image: nestjs-api
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - xaldigital
    restart: unless-stopped

networks:
  xaldigital:
    driver: bridge